Add the openhim channel for the covid19 case outcome
jembi/who-covid19-surveillance-package pull request #16
Opened 2021-05-31 14:39 UTC by bradsawadye

This is the channel that handles the storing of the Covid19 case outcome in FHIR and DHIS2

DSC19-145 DSC19-111

2021-06-08 14:48 UTC, MattyJ007 requested changes
Looking great - just two Observations that need to be merged together.
Very good commit message 💯

2021-06-08 14:48 UTC, MattyJ007 commented on docker/importer/volume/surveillance-mediator/case-outcome/endpoint-flattener.json
> +    "constants.outcomeAsympDateCoding": "observations[1].coding",
The effectiveDateTime field should be part of the Observation with the valueCoding - it's not a separate chunk of info.

2021-06-08 14:48 UTC, MattyJ007 commented on docker/importer/volume/surveillance-mediator/case-outcome/endpoint-flattener.json
> +    "constants.outcomeLabResultCoding": "observations[9].coding",
This data relates to one Observation

2021-06-08 18:25 UTC, bradsawadye commented on docker/importer/volume/surveillance-mediator/case-outcome/endpoint-flattener.json
> +    "constants.outcomeLabResultCoding": "observations[9].coding",
Addressed

2021-06-08 18:25 UTC, bradsawadye commented on docker/importer/volume/surveillance-mediator/case-outcome/endpoint-flattener.json
> +    "constants.outcomeAsympDateCoding": "observations[1].coding",
Addressed

2021-06-14 12:23 UTC, MattyJ007 approved these changes
Looks good

2021-06-14 12:23 UTC, MattyJ007 commented on docker/importer/volume/surveillance-mediator/case-outcome/endpoint-composition.json
> +    "requestBody.compositionDate": "composition.resource.date",
@bradsawadye This date field doesn't appear to be coming through in the final Composition
```suggestion
    "requestBody.data.compositionDate": "composition.resource.date",
```

I think it's the nesting

2021-06-14 12:23 UTC, merged